namespace MyTested.Mvc.Tests.BuildersTests.ActionResultsTests.HttpBadRequestTests
{
    using Exceptions;
    using Setups.Controllers;
    using Xunit;
    
    public class BadRequestErrorMessageTestBuilderTests
    {
        // TODO: errors are changed
        //[Fact]
        //public void ThatEqualsShouldNotThrowExceptionWithProperErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .ThatEquals("Bad request");
        //}

        //[Fact]
        //[ExpectedException(
        //    typeof(BadRequestResultAssertionException),
        //    ExpectedMessage = "When calling BadRequestWithErrorAction action in MvcController expected bad request error message to be 'Bad', but instead found 'Bad request'.")]
        //public void ThatEqualsShouldThrowExceptionWithIncorrectErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .ThatEquals("Bad");
        //}

        //[Fact]
        //public void BeginningWithShouldNotThrowExceptionWithProperErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .BeginningWith("Bad ");
        //}

        //[Fact]
        //[ExpectedException(
        //    typeof(BadRequestResultAssertionException),
        //    ExpectedMessage = "When calling BadRequestWithErrorAction action in MvcController expected bad request error message to begin with 'request', but instead found 'Bad request'.")]
        //public void BeginningWithShouldThrowExceptionWithIncorrectErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .BeginningWith("request");
        //}

        //[Fact]
        //public void EndingWithShouldNotThrowExceptionWithProperErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .EndingWith("request");
        //}

        //[Fact]
        //[ExpectedException(
        //    typeof(BadRequestResultAssertionException),
        //    ExpectedMessage = "When calling BadRequestWithErrorAction action in MvcController expected bad request error message to end with 'Bad', but instead found 'Bad request'.")]
        //public void EndingWithShouldThrowExceptionWithIncorrectErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .EndingWith("Bad");
        //}

        //[Fact]
        //public void ContainingShouldNotThrowExceptionWithProperErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .Containing("d r");
        //}

        //[Fact]
        //[ExpectedException(
        //    typeof(BadRequestResultAssertionException),
        //    ExpectedMessage = "When calling BadRequestWithErrorAction action in MvcController expected bad request error message to contain 'Another', but instead found 'Bad request'.")]
        //public void ContainingShouldThrowExceptionWithIncorrectErrorMessage()
        //{
        //    MyMvc
        //        .Controller<MvcController>()
        //        .Calling(c => c.BadRequestWithErrorAction())
        //        .ShouldReturn()
        //        .HttpBadRequest()
        //        .WithErrorMessage()
        //        .Containing("Another");
        //}
    }
}
